apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
spec:
  clusterIP: None
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: airflow-postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}